services:
  app:
    extends:
      file: docker-compose.dev.yml
      service: app
    device_requests:
      - driver: nvidia
        count: all
        capabilities:
          - gpu
    runtime: nvidia
