services:
  app:
    build:
      context: .
      args:
        INSTALL_HEAVY: "true"
    container_name: legal-bot-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - ./models:/models
      - ./chroma_db:/chroma_db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
