version: "3.8"
services:
  app:
    build:
      context: .
      target: dev
      args:
        - INSTALL_HEAVY=false
    image: legal-bot-dev:latest
    container_name: legal-bot-dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    # Монтируем только src, чтобы не было конфликтов имен пакетов
    volumes:
      - ./src:/app/src
      - ./models:/models
      - ./chroma_db:/chroma_db
    environment:
      - PYTHONPATH=/app/src
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
