version: "3.8"

services:
  app:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    device_requests:
      - driver: nvidia
        count: all
        capabilities:
          - gpu
