services:
  app:
    extends:
      file: docker-compose.yml
      service: app
    build:
      target: heavy
      args:
        INSTALL_HEAVY: "true"
    device_requests:
      - driver: nvidia
        count: all
        capabilities:
          - gpu
    runtime: nvidia
    environment:
      INSTALL_HEAVY: "true"
