services:
  app:
    build:
      context: .
      args:
        INSTALL_HEAVY: "true"
    container_name: legal-bot-app
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./models:/models
      - chroma_db:/chroma_db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  chroma_db:
