version: "3.8"
services:
  app:
    build:
      context: .
      args:
        - INSTALL_HEAVY=false
    image: legal-bot-dev:latest
    container_name: legal-bot-dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./models:/models
      - ./chroma_db:/chroma_db
    environment:
      - PYTHONUNBUFFERED=1
